import { TbBrandFramerMotion } from "react-icons/tb";
import {
  FaHtml5,
  FaCss3,
  FaJs,
  FaReact,
  FaNodeJs,
  FaGit,
  FaGithub,
  FaDocker,
  FaAws,
  FaLinux,
  FaBootstrap,
  FaSass,
} from "react-icons/fa";
import {
  SiTypescript,
  SiNextdotjs,
  SiExpress,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiFirebase,
  SiKubernetes,
  SiNginx,
  SiPostman,
  SiTailwindcss,
  SiRedux,
  SiGraphql,
} from "react-icons/si";

export const iconMapping = {
  html5: FaHtml5,
  css3: FaCss3,
  javascript: FaJs,
  react: FaReact,
  framerMotion: TbBrandFramerMotion,
  typescript: SiTypescript,
  nextjs: SiNextdotjs,
  nodejs: FaNodeJs,
  express: SiExpress,
  mongodb: SiMongodb,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  firebase: SiFirebase,
  git: FaGit,
  github: FaGithub,
  docker: FaDocker,
  kubernetes: SiKubernetes,
  aws: FaAws,
  nginx: SiNginx,
  linux: FaLinux,
  //   vscode: SiVisualstudiocode,
  postman: SiPostman,
  sass: FaSass,
  tailwind: SiTailwindcss,
  bootstrap: FaBootstrap,
  //   materialui: SiMaterialui,
  redux: SiRedux,
  graphql: SiGraphql,
};

export const iconAltMapping = [
  { icon: FaHtml5, alt: "HTML5" },
  { icon: FaCss3, alt: "CSS3" },
  { icon: FaJs, alt: "JavaScript" },
  { icon: FaReact, alt: "React" },
  { icon: TbBrandFramerMotion, alt: "Framer Motion" },
  { icon: SiTypescript, alt: "TypeScript" },
  { icon: SiNextdotjs, alt: "Next.js" },
  { icon: FaNodeJs, alt: "Node.js" },
  { icon: SiExpress, alt: "Express" },
  { icon: SiMongodb, alt: "MongoDB" },
  { icon: SiMysql, alt: "MySQL" },
  { icon: SiPostgresql, alt: "PostgreSQL" },
  { icon: SiFirebase, alt: "Firebase" },
  { icon: FaGit, alt: "Git" },
  { icon: FaGithub, alt: "GitHub" },
  { icon: FaDocker, alt: "Docker" },
  { icon: SiKubernetes, alt: "Kubernetes" },
  { icon: FaAws, alt: "AWS" },
  { icon: SiNginx, alt: "Nginx" },
  { icon: FaLinux, alt: "Linux" },
  { icon: SiPostman, alt: "Postman" },
  { icon: FaSass, alt: "Sass" },
  { icon: SiTailwindcss, alt: "Tailwind CSS" },
  { icon: FaBootstrap, alt: "Bootstrap" },
  { icon: SiRedux, alt: "Redux" },
  { icon: SiGraphql, alt: "GraphQL" },
];
