export const projectLinks = [
  {
    src: "/projects-images/hellotalk.png",
    title: "Hellotalk - A Realtime Chat App",
    description:
      "A full‑stack real‑time chat platform with one-to-one audio and video calling, group messaging, file sharing, and notifications. Built with React, Node.js, Socket.IO, MongoDB, and WebRTC, featuring a modern responsive UI and an admin dashboard.",
    link: "https://hellotalk.officialgopi.xyz/",
    techStack: [
      "React 19",
      "Vite 7",
      "Tailwind CSS 4",
      "Redux Toolkit + RTK Query",
      "React Router 7",
      "Node.js",
      "Express 5",
      "Socket.IO 4",
      "TypeScript",
      "Mongoose 8",
      "Zod",
      "Multer",
      "Cloudinary",
      "Winston",
      "MongoDB",
      "WebRTC",
      "Chart.js",
    ],
    githubLink: "https://github.com/OfficialGopi/hellotalk",
  },
  {
    src: "/projects-images/coderroute.png",
    title: "CoderRoute",
    description:
      "A MERN-based LeetCode-style app for solving coding problems, tracking streaks, and personalized revision. Features a live Judge0-powered code editor, AI assistant for hints and debugging, full user auth, admin problem management, and a responsive TailwindCSS + Framer Motion UI.",
    link: "https://coderroute.officialgopi.xyz/",
    techStack: [
      "React",
      "TailwindCss",
      "NodeJS",
      "ExpressJS",
      "Judge0",
      "PostgreSQL",
      "Prisma",
      "Groq AI",
    ],
    githubLink: "https://github.com/OfficialGopi/coderroute-main",
  },
  {
    src: "/projects-images/thumbgen.png",
    title: "Thumbgen - An AI Powered Thumbnail Generator",
    description:
      "An AI-powered thumbnail generator that creates eye-catching, customizable thumbnails from your images and text. Features drag-and-drop upload, style presets, font customization, and a responsive TailwindCSS + Framer Motion UI for a smooth design experience.",
    link: "https://thumbgen.officialgopi.xyz/",
    techStack: [
      "React",
      "TailwindCss",
      "Framer Motion",
      "Shadcn UI",
      "NodeJS",
      "ExpressJS",
      "Passport OAUTH2",
      "PostgreSQL",
      "Prisma",
      "Groq AI",
      "Gemini Flash 2.5 preview",
      "Gemini - Nano Banana",
    ],
    githubLink: "https://github.com/OfficialGopi/thumbgen",
  },
];
